extends:
  - './node_modules/@neo9/n9-coding-style/.eslintrc.yaml'
rules:
  'rxjs/no-implicit-any-catch': off
  'no-param-reassign': off
  'rxjs/no-nested-subscribe': off
  '@typescript-eslint/no-floating-promises': off
  '@typescript-eslint/naming-convention': off
  '@typescript-eslint/member-ordering': off
